server:
  port: 8466
logging:
  file: /java/C2S_LOGS/provider-ui-api/provider-ui-api.log
info:
  component: Provider Ui Api
ribbon:
  ReadTimeout: 50000
hystrix.command.default.execution.timeout.enabled: false
security:
  oauth2:
    client:
      client-id: provider-ui-api
# The configuration used for Provider UI
c2s:
  provider-ui:
    provider-permissions:
      consent-sign-enabled: false
      consent-revoke-enabled: false
      user-activation-enabled: true
      segmentation-enabled: true
      registration:
        duplicate-check-enabled: false
      patient-list-card-enabled: true
      patient-search:
        first-name-required: false
        last-name-required: true
        gender-required: false
        date-of-birth-required: false
        patient-id-required: false
    default-patient-identifier-system: https://bhits.github.io/consent2share
  provider-ui-api:
    # Please configure valid config below to connect to UAA server
    # Configure base-url, client-id, client-secret per environment
    oauth2:
      base-url: http://localhost/uaa
      client:
        client-id: provider-ui
        client-secret: changeit
    consent-management:
      active-attestation-term-id: 3
      active-revocation-term-id: 1
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl-default
server:
  context-path: /provider-ui-api